[package]
name = "yrba"
description = "Incremental remote backups made simple!"
authors = ["Lilith Roth <lilith@roth.systems>"]
version = "2.1.1"
edition = "2024"
readme = "README.md"
repository = "https://github.com/lilith-roth/yrba"
documentation = "https://yrba.roth.systems/"
license = "GPL-3.0-only"
keywords = ["backup", "sftp", "nfs"]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/yrba", dest = "/bin/yrba", mode = "755" },
    { source = "config.example.toml", dest = "/etc/default/yrba.toml", mode = "644" },
    { source = "systemd/*", dest = "/usr/lib/systemd/system/", mode = "644" },
]

[package.metadata.deb]
license-file = "LICENSE"
assets = [
    # target/release path is special, and gets replaced by cargo-deb with the actual target dir path.
    ["target/release/yrba", "usr/bin/", "755"],
    { source = "config.example.toml", dest = "/etc/default/yrba.toml", mode = "644" },
#    { source = "systemd/*", dest = "/usr/lib/systemd/system/", mode = "644" },
]
maintainer-scripts = "systemd/"
systemd-units = [
    { unit-name = "yrba", enable = false },
    { unit-name = "yrba.daily", enable = false },
    { unit-name = "yrba.weekly", enable = false },
    { unit-name = "yrba.monthly", enable = false }
]

[lints.clippy]
pedantic = "warn"

[features]
vendored-openssl = [ "openssl" ]

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4.5.51", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.4", features = ["tracing", "log", "default"] }
console = "0.16.1"
dirs = "6.0.0"
env_logger = "0.11.8"
flate2 = "1.1.5"
log = "0.4.28"
nix = { version = "0.30.1", features = ["user"] }
openssl = { version = "0.10.75", features = ["vendored"], optional = true }
serde = { version = "1.0.228", features = ["derive"] }
shellexpand = "3.1.1"
ssh2 = "0.9.5"
tar = "0.4.44"
toml = { version = "0.9.8", features = ["parse"] }
url = "2.5.7"
whoami = "1.6.1"
tempfile = "3.23.0"
